# -*- coding: utf-8 -*-
"""finalIngres.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1abCaEFXnYbxlOhfDHyb7LTmqQTM8Cre9
"""

# !pip install sentence-transformers faiss-cpu google-generativeai pandas numpy

import os
import numpy as np
import pandas as pd
import faiss

from sentence_transformers import SentenceTransformer
import google.generativeai as genai

# from google.colab import files
# files.upload()

def load_texts(path):
    with open(path, "r", encoding="utf-8") as f:
        texts = f.read().split("\n\n")
    return [t.strip() for t in texts if t.strip()]

block_texts = load_texts("block_data.txt")
state_texts = load_texts("state_data.txt")

documents = block_texts + state_texts
print("Total documents:", len(documents))

embed_model = SentenceTransformer("all-MiniLM-L6-v2")

embeddings = embed_model.encode(documents, show_progress_bar=True)
dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)
index.add(np.array(embeddings))

print("FAISS index size:", index.ntotal)

state_df = pd.read_csv("state_data.csv")

state_df.columns = state_df.columns.str.lower().str.strip()
state_df["category"] = state_df["category"].str.replace("  ", " ").str.strip()


state_df["category"] = (
    state_df["category"]
    .astype(str)
    .str.lower()
    .str.replace("-", " ", regex=False)
    .str.replace("_", " ", regex=False)
    .str.strip()
)

state_df["year"] = state_df["year"].astype(int)

block_df = pd.read_csv("block_data.csv")
for df in [block_df, state_df]:
    df.columns = df.columns.str.lower().str.strip()
    df["category"] = (
        df["category"]
        .astype(str)
        .str.lower()
        .str.replace("-", " ", regex=False)
        .str.replace("_", " ", regex=False)
        .str.strip()
    )
    df["year"] = df["year"].astype(int)

def normalize_category(x):
    return (
        str(x)
        .lower()
        .replace("-", " ")
        .replace("_", " ")
        .replace("\u00a0", " ")   # non-breaking space fix
        .replace("  ", " ")
        .strip()
    )

state_df["category"] = state_df["category"].apply(normalize_category)
block_df["category"] = block_df["category"].apply(normalize_category)

os.environ["GOOGLE_API_KEY"] = "AIzaSyDu4rYdLSTYh6aerSUeVY60YPaWm6WbgOg"
genai.configure(api_key=os.environ["GOOGLE_API_KEY"])

llm = genai.GenerativeModel("models/gemini-2.5-flash")

# def ask_bot(question, k=5):
#     q_vec = embed_model.encode([question])
#     D, I = index.search(np.array(q_vec), k=k)

#     context = "\n".join([documents[i] for i in I[0]])

#     prompt = f"""
# You are a groundwater expert.
# Answer strictly from the context below.

# Context:
# {context}

# Question:
# {question}
# """
#     return llm.generate_content(prompt).text
def ask_bot(question, k=5):
    try:
        q_vec = embed_model.encode([question])
        D, I = index.search(np.array(q_vec), k=k)

        context = "\n".join([documents[i] for i in I[0]])

        prompt = f"""
You are a groundwater expert.
Answer strictly from the context below.

Context:
{context}

Question:
{question}
"""
        response = llm.generate_content(prompt)

        if response and hasattr(response, "text") and response.text:
            return response.text.strip()

        return "Sorry, I could not generate an explanation for this query."

    except Exception as e:
        if "429" in str(e):
            return (
                "LLM rate limit exceeded. "
                "Please retry after some time or ask a data-based query."
            )
        return f"LLM error while answering: {e}"



def full_state_report(state_name, question):
    df = state_df[state_df["state"].str.lower() == state_name.lower()]

    # year optional
    for y in [2019, 2020, 2021, 2022]:
        if str(y) in question:
            df = df[df["year"] == y]

    if df.empty:
        return f"No groundwater data found for {state_name}."

    year = int(df["year"].iloc[0])

    summary = df["category"].value_counts()
    avg_rain = round(df["rainfall_mm"].mean(), 2)
    total_recharge = round(df["ground_water_recharge_ham"].sum(), 2)
    total_extraction = round(df["ground_water_extraction_ham"].sum(), 2)
    avg_stage = round(df["stage_percent"].mean(), 2)

    lines = [
        f"Groundwater condition in {state_name} ({year}):",
        f"- Average annual rainfall: {avg_rain} mm",
        f"- Total groundwater recharge: {total_recharge} ham",
        f"- Total groundwater extraction: {total_extraction} ham",
        f"- Average stage of extraction: {avg_stage} %",
        "",
        "Category-wise status:"
    ]

    for cat, cnt in summary.items():
        lines.append(f"- {cat.title()}: {cnt} blocks")

    return "\n".join(lines)

def block_report(question):
    q = question.lower()
    df = block_df.copy()

    # year
    for y in [2019, 2020, 2021, 2022]:
        if str(y) in q:
            df = df[df["year"] == y]

    for b in df["block"].dropna().astype(str).unique():
        if b.lower() in q:
            row = df[df["block"] == b].iloc[0]

            return f"""
Country: {row['country']}
State: {row['state']}
District: {row['district']}
Block: {row['block']}
Year: {row['year']}
Annual Rainfall: {row['rainfall_mm']} mm
Groundwater Recharge: {row['ground_water_recharge_ham']} ham
Groundwater Extraction: {row['ground_water_extraction_ham']} ham
Stage of Extraction: {round(row['stage_percent'],2)} %
Category: {row['category'].title()}
""".strip()

    return None

def answer_from_csv(question):
    q = question.lower()
    df = state_df.copy()

    for y in [2019, 2020, 2021, 2022]:
        if str(y) in q:
            df = df[df["year"] == y]

    if "over" in q:
        df = df[df["category"].str.contains("over", case=False)]
    elif "semi" in q:
        df = df[df["category"].str.contains("semi", case=False)]
    elif "critical" in q:
        df = df[df["category"].str.contains("critical", case=False)]
    elif "safe" in q:
        df = df[df["category"].str.contains("safe", case=False)]

    if df.empty:
        return "No matching records found."

    return ", ".join(sorted(df["state"].unique()))

def chatbot(question):
    q = question.lower().strip()

    # 1️⃣ Conceptual → Gemini
    if any(w in q for w in ["why", "impact", "concern", "explain", "effect"]):
        return ask_bot(question)

    # 2️⃣ Year (optional)
    year = None
    for y in [2019, 2020, 2021, 2022]:
        if str(y) in q:
            year = y
            break

    # 3️⃣ Category
    category = None
    if "over" in q and "exploit" in q:
        category = "over exploited"
    elif "semi" in q:
        category = "semi critical"
    elif "critical" in q:
        category = "critical"
    elif "safe" in q:
        category = "safe"

    # 4️⃣ BLOCK queries
    if "block" in q and category:
        df = block_df.copy()
        if year:
            df = df[df["year"] == year]
        df = df[df["category"] == category]

        if "how many" in q:
            return f"Number of {category} blocks{f' in {year}' if year else ''}: {df['block'].nunique()}"

        return f"{category.title()} blocks{f' in {year}' if year else ''}: " + ", ".join(sorted(df["block"].unique()))

    # 5️⃣ STATE aggregation
    if "state" in q and category:
        df = state_df.copy()
        if year:
            df = df[df["year"] == year]
        df = df[df["category"] == category]

        if "how many" in q:
            return f"Number of {category} states{f' in {year}' if year else ''}: {df['state'].nunique()}"

        return f"{category.title()} states{f' in {year}' if year else ''}: " + ", ".join(sorted(df["state"].unique()))

    # 6️⃣ DEFAULT → old behaviour (RAG)
    return ask_bot(question)

# print(chatbot("how many over-exploited state in 2019"))

# print(chatbot("What is the groundwater condition in Bihar in 2019?"))
# print(chatbot("bihar 2019"))



# print(chatbot("what is the groundwater condition in bihar in 2020?"))
# print(chatbot("Which block is over exploited in 2019?"))
# print(chatbot("Which state is over exploited in 2019"))

# print(chatbot("In 2019, what was the groundwater status of Bawani Khera block in Haryana?"))

# print(chatbot("In 2019, what was the groundwater status of hoskote block give me full detail?"))
# print(chatbot("Tell me groundwater details of Bawani Khera, Haryana?"))
# print(chatbot("Tell me groundwater details of Bawani Khera, Haryana for 2020?"))
# print(chatbot("How many states are safe in 2020?"))
# print(chatbot("Why is over-exploitation of groundwater a concern?"))
# print(chatbot("Which blocks is semi critical in 2019"))


# print(chatbot("asdjkhaskdh"))
# print(chatbot(""))
# print(chatbot("How many block are semi critical in 2020?"))
# print(chatbot("Which state are semi critical in 2021?"))

def chatbot_api(query):
    return chatbot(query)

chatbot_api("How many states are over exploited in 2019?")

